name: portfolio

services:
  backend:
    container_name: backend
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
    network_mode: host
    env_file:
      - .env
    restart: unless-stopped
    pull_policy: always
